import { loadLocations, saveLocations } from "../../../data/repository.js";
import { generateLocationBackground } from "../../../images/portraitGenerator.js";
import { syncLocationToVectorDb } from "../../../vectorSync.js";

export async function resolve(scene, oldLocId){
    if (scene.newLocation && scene.newLocation.id) {
          const currentLocations = await loadLocations();
          const cleanLocId = scene.newLocation.id.toLowerCase().replace(/[^a-z0-9]/g, '');
          const exists = currentLocations.some(loc => loc.id === cleanLocId);
    
          if (!exists) {
            console.log(`[Database] Registering new Location generated by Dungeon Master: ${scene.newLocation.name}`);
            
            // Resolve parent connection node and distance
            const parentLocId = String(scene.newLocation.connectedTo || oldLocId).trim().toLowerCase();
            const distance = Number(scene.newLocation.distance || 5);
            
            const cleanLocation = {
              id: cleanLocId,
              name: scene.newLocation.name,
              asset: `assets/locations/${cleanLocId}.png`,
              prompt: scene.newLocation.prompt,
              ambient: scene.newLocation.ambient || 'Silencio medieval y misterio en el ambiente.',
              connections: [
                { to: parentLocId, distance: distance }
              ]
            };
    
            // Mutate parent in current list to establish the bidirectional connection
            const parentLoc = currentLocations.find(l => l.id === parentLocId);
            if (parentLoc) {
              if (!parentLoc.connections) parentLoc.connections = [];
              const connExists = parentLoc.connections.some(c => c.to === cleanLocId);
              if (!connExists) {
                parentLoc.connections.push({ to: cleanLocId, distance: distance });
              }
            }
    
            const updatedLocations = [...currentLocations, cleanLocation];
            await saveLocations(updatedLocations);
    
            // Generate location background synchronously — image is ready before response is sent
            const generated = await generateLocationBackground(cleanLocation.id, cleanLocation.prompt);
    
            // Attach a cache-busted assetUrl to the scene so the client gets the final URL
            const ts = Date.now();
            scene.newLocation.id = cleanLocId;
            scene.newLocation.assetUrl = generated
              ? `assets/locations/${cleanLocId}.png?t=${ts}`
              : null;
    
            // Sync new Location to Vector DB
            await syncLocationToVectorDb(cleanLocation);
          }
        }
}

export async function updateLocationImage(scene){
    if (scene.updateLocationImage && scene.updateLocationImage.locationId && scene.updateLocationImage.locationId.trim() !== '') {
          const locIdToUpdate = String(scene.updateLocationImage.locationId).trim().toLowerCase();
          const newPrompt = String(scene.updateLocationImage.prompt || '').trim();
          
          const currentLocations = await loadLocations();
          const existingLoc = currentLocations.find((loc) => loc.id === locIdToUpdate);
          if (existingLoc && newPrompt) {
            console.log(`[Server] Overwriting background image for location: ${locIdToUpdate} with prompt: "${newPrompt}"`);
            existingLoc.prompt = newPrompt;
            await saveLocations(currentLocations);
    
            // Generate the new background image synchronously to overwrite the file
            await generateLocationBackground(locIdToUpdate, newPrompt);
            
            // Attach updated location info to the payload response so the client knows it changed
            const ts = Date.now();
            scene.locationUpdate = {
              id: locIdToUpdate,
              prompt: newPrompt,
              assetUrl: `assets/locations/${locIdToUpdate}.png?t=${ts}`
            };
    
            // Re-sync to Vector DB
            await syncLocationToVectorDb(existingLoc);
          }
        }
}