import { loadNpcs, saveNpcs } from "../../../data/repository.js";
import { generateNpcPortraits } from "../../../images/portraitGenerator.js";
import { syncNpcToVectorDb } from "../../../vectorSync.js";
import { orchestrateNpcTurn } from "../../../helpers/instructions/npcOrchestrator.js";
import { vectorManager } from "../../../config/aiProviders.js";
import * as sceneStreamer from "../scene/sceneStreamer.js";

export async function resolve(scene, locationId) {
    if (scene.newNpc && scene.newNpc.id) {
       const currentNpcs = await loadNpcs();
       const cleanId = scene.newNpc.id.toLowerCase().replace(/[^a-z0-9]/g, '');
       const matchedNpc = currentNpcs.find(npc => npc.id === cleanId || npc.name.toLowerCase().trim() === scene.newNpc.name.toLowerCase().trim());
       
       if (matchedNpc) {
         console.log(`[Database] Collision detected for new NPC request: "${scene.newNpc.name}" (ID in request: "${scene.newNpc.id}"). Remapping all references to existing NPC ID "${matchedNpc.id}".`);
         // Remap in participantIds
         scene.participantIds = scene.participantIds.map(id => id === scene.newNpc.id ? matchedNpc.id : id);
         // Remap in messages speakerId
         scene.messages = scene.messages.map(m => m.speakerId === scene.newNpc.id ? { ...m, speakerId: matchedNpc.id } : m);
         // Nullify newNpc
         scene.newNpc = null;
       } else {
         console.log(`[Database] Registering new NPC generated by Dungeon Master: ${scene.newNpc.name}`);
         
         const cleanNpc = {
           id: cleanId,
           name: scene.newNpc.name,
           role: scene.newNpc.role,
           locationId: scene.newNpc.locationId || locationId,
           personality: scene.newNpc.personality,
           secret: scene.newNpc.secret,
           hint: scene.newNpc.hint,
           color: scene.newNpc.color || '#7c7c7c',
           skin: scene.newNpc.skin || '#dfab8f',
           hair: scene.newNpc.hair || '#2b1b17',
           outfit: scene.newNpc.outfit || 'civic',
           suggestions: Array.isArray(scene.newNpc.suggestions) ? scene.newNpc.suggestions : ["Hablar", "Preguntar"]
         };

         const updatedNpcs = [...currentNpcs, cleanNpc];
         await saveNpcs(updatedNpcs);

         // Generate portraits synchronously so they exist when client receives the response
         await generateNpcPortraits(
           cleanNpc.id,
           cleanNpc.color,
           cleanNpc
         );

         // Sync new NPC to Vector DB
         await syncNpcToVectorDb(cleanNpc);
       }
    }
}

export async function orchestrate(context, activeConversationManager, res) {
    const participants = context.scene.participantIds
        .map(id => context.npcs.find(npc => npc.id === id))
        .filter(Boolean);

    if (participants.length > 0) {
        const location = context.locations.find(loc => loc.id === context.scene.locationId);
        const iterator = orchestrateNpcTurn({
            participants,
            location,
            state: context.state,
            playerText: context.playerText,
            history: context.history,
            currentNpcs: context.npcs,
            client: activeConversationManager.client,
            isGemini: activeConversationManager.isGemini,
            mainModel: activeConversationManager.model,
            vectorManager,
            sceneContext: context.scene.sceneContext || context.scene.narration
        });

        let result = await iterator.next();
        while (!result.done) {
            const chunk = result.value;
            if (res) {
                sceneStreamer.sendNpcResponse(res, {
                    speakerId: chunk.npcId,
                    line: chunk.dialogue,
                    expression: chunk.expression,
                    actions: chunk.actions
                });
            }
            result = await iterator.next();
        }
        const aggregated = result.value;

        if (aggregated) {
            // Ensure array fields are initialized
            context.scene.messages = context.scene.messages || [];
            context.scene.relationshipDeltas = context.scene.relationshipDeltas || {};
            context.scene.trustDeltas = context.scene.trustDeltas || {};
            context.scene.inventoryDeltas = context.scene.inventoryDeltas || [];
            context.scene.questUpdates = context.scene.questUpdates || [];

            // Merge NPC dialogue messages
            if (Array.isArray(aggregated.npcMessages)) {
                context.scene.messages.push(...aggregated.npcMessages);
            }

            // Merge relationship and trust deltas (accumulate/add)
            if (Array.isArray(aggregated.relationshipDeltas)) {
                aggregated.relationshipDeltas.forEach(d => {
                    context.scene.relationshipDeltas[d.npcId] = (context.scene.relationshipDeltas[d.npcId] || 0) + d.delta;
                });
            }
            if (Array.isArray(aggregated.trustDeltas)) {
                aggregated.trustDeltas.forEach(d => {
                    context.scene.trustDeltas[d.npcId] = (context.scene.trustDeltas[d.npcId] || 0) + d.delta;
                });
            }

            // Merge inventory deltas
            if (Array.isArray(aggregated.inventoryDeltas)) {
                context.scene.inventoryDeltas.push(...aggregated.inventoryDeltas);
            }

            // Merge gold
            if (aggregated.goldDelta) {
                context.scene.goldDelta = (context.scene.goldDelta || 0) + aggregated.goldDelta;
            }

            // Merge quest updates
            if (Array.isArray(aggregated.questUpdates)) {
                context.scene.questUpdates.push(...aggregated.questUpdates);
            }

            // Merge generateQuest
            if (aggregated.generateQuest) {
                context.scene.generateQuest = aggregated.generateQuest;
            }

            // Handle wantsToLeaveIds
            if (Array.isArray(aggregated.wantsToLeaveIds) && aggregated.wantsToLeaveIds.length > 0) {
                aggregated.wantsToLeaveIds.forEach(id => {
                    context.scene.participantIds = context.scene.participantIds.filter(pId => pId !== id);
                    const npcName = context.npcs.find(n => n.id === id)?.name || id;
                    context.scene.messages.push({
                        speakerId: 'narrator',
                        line: `[Especial] ${npcName} se retira de la escena.`,
                        expression: 'neutral'
                    });
                });
            }
        }
    }
}
